package com.artcanvaszambia.backend.security;

public enum Permission {
    USERS_RESET_PASSWORD,
    USERS_MANAGE_PERMISSIONS,
    USERS_MANAGE_SESSIONS,
    CATEGORIES_MANAGE,
    ARTWORKS_MODERATE,
    ARTWORKS_PUBLISH,
    SUPPLIES_MODERATE,
    SUPPLIES_PUBLISH,
    CLASSES_MODERATE,
    CLASSES_PUBLISH,
    EXHIBITIONS_MODERATE,
    EXHIBITIONS_PUBLISH,
    COMMISSIONS_MODERATE,
    COMMISSIONS_ACCEPT,
    ORDERS_MANAGE,
    PAYOUTS_VIEW,
    PAYOUTS_APPROVE,
    PAYOUTS_REQUEST,
    PLATFORM_SETTINGS_VIEW,
    PLATFORM_SETTINGS_EDIT,
    WALLET_VIEW_BALANCE
}
