CREATE TABLE role_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role TEXT NOT NULL CHECK (role IN ('SUPER_ADMIN','ADMIN','ARTIST','INSTRUCTOR','SUPPLIER','STUDENT','CUSTOMER')),
    permission TEXT NOT NULL CHECK (permission IN (
        'USERS_RESET_PASSWORD','USERS_MANAGE_PERMISSIONS',
        'CATEGORIES_MANAGE',
        'ARTWORKS_MODERATE','ARTWORKS_PUBLISH',
        'SUPPLIES_MODERATE','SUPPLIES_PUBLISH',
        'CLASSES_MODERATE','CLASSES_PUBLISH',
        'EXHIBITIONS_MODERATE','EXHIBITIONS_PUBLISH',
        'COMMISSIONS_MODERATE','COMMISSIONS_ACCEPT',
        'ORDERS_MANAGE',
        'PAYOUTS_VIEW','PAYOUTS_APPROVE','PAYOUTS_REQUEST',
        'PLATFORM_SETTINGS_VIEW','PLATFORM_SETTINGS_EDIT',
        'WALLET_VIEW_BALANCE'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(role, permission)
);

CREATE TABLE user_permission_overrides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission TEXT NOT NULL CHECK (permission IN (
        'USERS_RESET_PASSWORD','USERS_MANAGE_PERMISSIONS',
        'CATEGORIES_MANAGE',
        'ARTWORKS_MODERATE','ARTWORKS_PUBLISH',
        'SUPPLIES_MODERATE','SUPPLIES_PUBLISH',
        'CLASSES_MODERATE','CLASSES_PUBLISH',
        'EXHIBITIONS_MODERATE','EXHIBITIONS_PUBLISH',
        'COMMISSIONS_MODERATE','COMMISSIONS_ACCEPT',
        'ORDERS_MANAGE',
        'PAYOUTS_VIEW','PAYOUTS_APPROVE','PAYOUTS_REQUEST',
        'PLATFORM_SETTINGS_VIEW','PLATFORM_SETTINGS_EDIT',
        'WALLET_VIEW_BALANCE'
    )),
    granted BOOLEAN NOT NULL,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, permission)
);
CREATE INDEX idx_user_permission_overrides_user ON user_permission_overrides(user_id);


