ALTER TABLE role_permissions DROP CONSTRAINT role_permissions_permission_check;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_permission_check CHECK (permission IN (
    'USERS_RESET_PASSWORD','USERS_MANAGE_PERMISSIONS','USERS_MANAGE_SESSIONS',
    'CATEGORIES_MANAGE',
    'ARTWORKS_MODERATE','ARTWORKS_PUBLISH',
    'SUPPLIES_MODERATE','SUPPLIES_PUBLISH',
    'CLASSES_MODERATE','CLASSES_PUBLISH',
    'EXHIBITIONS_MODERATE','EXHIBITIONS_PUBLISH',
    'COMMISSIONS_MODERATE','COMMISSIONS_ACCEPT',
    'ORDERS_MANAGE',
    'PAYOUTS_VIEW','PAYOUTS_APPROVE','PAYOUTS_REQUEST',
    'PLATFORM_SETTINGS_VIEW','PLATFORM_SETTINGS_EDIT',
    'WALLET_VIEW_BALANCE'
));

ALTER TABLE user_permission_overrides DROP CONSTRAINT user_permission_overrides_permission_check;
ALTER TABLE user_permission_overrides ADD CONSTRAINT user_permission_overrides_permission_check CHECK (permission IN (
    'USERS_RESET_PASSWORD','USERS_MANAGE_PERMISSIONS','USERS_MANAGE_SESSIONS',
    'CATEGORIES_MANAGE',
    'ARTWORKS_MODERATE','ARTWORKS_PUBLISH',
    'SUPPLIES_MODERATE','SUPPLIES_PUBLISH',
    'CLASSES_MODERATE','CLASSES_PUBLISH',
    'EXHIBITIONS_MODERATE','EXHIBITIONS_PUBLISH',
    'COMMISSIONS_MODERATE','COMMISSIONS_ACCEPT',
    'ORDERS_MANAGE',
    'PAYOUTS_VIEW','PAYOUTS_APPROVE','PAYOUTS_REQUEST',
    'PLATFORM_SETTINGS_VIEW','PLATFORM_SETTINGS_EDIT',
    'WALLET_VIEW_BALANCE'
));



CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
    actor_label TEXT,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id UUID,
    target_label TEXT,
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at DESC);
