/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as SellRouteImport } from './routes/sell'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliesIndexRouteImport } from './routes/supplies.index'
import { Route as ExhibitionsIndexRouteImport } from './routes/exhibitions.index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as SuppliesSlugRouteImport } from './routes/supplies.$slug'
import { Route as ExhibitionsSlugRouteImport } from './routes/exhibitions.$slug'
import { Route as ClassesSlugRouteImport } from './routes/classes.$slug'
import { Route as ArtworksSlugRouteImport } from './routes/artworks.$slug'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedDashboardUploadRouteImport } from './routes/_authenticated/dashboard.upload'
import { Route as AuthenticatedDashboardTicketsRouteImport } from './routes/_authenticated/dashboard.tickets'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardNewSupplyRouteImport } from './routes/_authenticated/dashboard.new-supply'
import { Route as AuthenticatedDashboardNewExhibitionRouteImport } from './routes/_authenticated/dashboard.new-exhibition'
import { Route as AuthenticatedDashboardNewClassRouteImport } from './routes/_authenticated/dashboard.new-class'
import { Route as AuthenticatedDashboardCommissionsRouteImport } from './routes/_authenticated/dashboard.commissions'
import { Route as AuthenticatedDashboardArtworksRouteImport } from './routes/_authenticated/dashboard.artworks'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesIndexRoute = SuppliesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliesRoute,
} as any)
const ExhibitionsIndexRoute = ExhibitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassesRoute,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const SuppliesSlugRoute = SuppliesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SuppliesRoute,
} as any)
const ExhibitionsSlugRoute = ExhibitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClassesRoute,
} as any)
const ArtworksSlugRoute = ArtworksSlugRouteImport.update({
  id: '/artworks/$slug',
  path: '/artworks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtistsRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardUploadRoute =
  AuthenticatedDashboardUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTicketsRoute =
  AuthenticatedDashboardTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewSupplyRoute =
  AuthenticatedDashboardNewSupplyRouteImport.update({
    id: '/new-supply',
    path: '/new-supply',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewExhibitionRoute =
  AuthenticatedDashboardNewExhibitionRouteImport.update({
    id: '/new-exhibition',
    path: '/new-exhibition',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewClassRoute =
  AuthenticatedDashboardNewClassRouteImport.update({
    id: '/new-class',
    path: '/new-class',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommissionsRoute =
  AuthenticatedDashboardCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArtworksRoute =
  AuthenticatedDashboardArtworksRouteImport.update({
    id: '/artworks',
    path: '/artworks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/classes': typeof ClassesRouteWithChildren
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/supplies': typeof SuppliesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/sales': typeof AuthenticatedSalesRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/supplies/$slug': typeof SuppliesSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/dashboard/artworks': typeof AuthenticatedDashboardArtworksRoute
  '/dashboard/commissions': typeof AuthenticatedDashboardCommissionsRoute
  '/dashboard/new-class': typeof AuthenticatedDashboardNewClassRoute
  '/dashboard/new-exhibition': typeof AuthenticatedDashboardNewExhibitionRoute
  '/dashboard/new-supply': typeof AuthenticatedDashboardNewSupplyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/tickets': typeof AuthenticatedDashboardTicketsRoute
  '/dashboard/upload': typeof AuthenticatedDashboardUploadRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/supplies/$slug': typeof SuppliesSlugRoute
  '/artists': typeof ArtistsIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/exhibitions': typeof ExhibitionsIndexRoute
  '/supplies': typeof SuppliesIndexRoute
  '/dashboard/artworks': typeof AuthenticatedDashboardArtworksRoute
  '/dashboard/commissions': typeof AuthenticatedDashboardCommissionsRoute
  '/dashboard/new-class': typeof AuthenticatedDashboardNewClassRoute
  '/dashboard/new-exhibition': typeof AuthenticatedDashboardNewExhibitionRoute
  '/dashboard/new-supply': typeof AuthenticatedDashboardNewSupplyRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/tickets': typeof AuthenticatedDashboardTicketsRoute
  '/dashboard/upload': typeof AuthenticatedDashboardUploadRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/classes': typeof ClassesRouteWithChildren
  '/commissions': typeof CommissionsRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/supplies': typeof SuppliesRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/supplies/$slug': typeof SuppliesSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/_authenticated/dashboard/artworks': typeof AuthenticatedDashboardArtworksRoute
  '/_authenticated/dashboard/commissions': typeof AuthenticatedDashboardCommissionsRoute
  '/_authenticated/dashboard/new-class': typeof AuthenticatedDashboardNewClassRoute
  '/_authenticated/dashboard/new-exhibition': typeof AuthenticatedDashboardNewExhibitionRoute
  '/_authenticated/dashboard/new-supply': typeof AuthenticatedDashboardNewSupplyRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/tickets': typeof AuthenticatedDashboardTicketsRoute
  '/_authenticated/dashboard/upload': typeof AuthenticatedDashboardUploadRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artists'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/classes'
    | '/commissions'
    | '/contact'
    | '/exhibitions'
    | '/help'
    | '/privacy'
    | '/sell'
    | '/supplies'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/sales'
    | '/artists/$id'
    | '/artworks/$slug'
    | '/classes/$slug'
    | '/exhibitions/$slug'
    | '/supplies/$slug'
    | '/artists/'
    | '/classes/'
    | '/exhibitions/'
    | '/supplies/'
    | '/dashboard/artworks'
    | '/dashboard/commissions'
    | '/dashboard/new-class'
    | '/dashboard/new-exhibition'
    | '/dashboard/new-supply'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/upload'
    | '/orders/$orderId'
    | '/dashboard/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/commissions'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/sell'
    | '/terms'
    | '/admin'
    | '/sales'
    | '/artists/$id'
    | '/artworks/$slug'
    | '/classes/$slug'
    | '/exhibitions/$slug'
    | '/supplies/$slug'
    | '/artists'
    | '/classes'
    | '/exhibitions'
    | '/supplies'
    | '/dashboard/artworks'
    | '/dashboard/commissions'
    | '/dashboard/new-class'
    | '/dashboard/new-exhibition'
    | '/dashboard/new-supply'
    | '/dashboard/profile'
    | '/dashboard/tickets'
    | '/dashboard/upload'
    | '/orders/$orderId'
    | '/dashboard'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/artists'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/classes'
    | '/commissions'
    | '/contact'
    | '/exhibitions'
    | '/help'
    | '/privacy'
    | '/sell'
    | '/supplies'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/sales'
    | '/artists/$id'
    | '/artworks/$slug'
    | '/classes/$slug'
    | '/exhibitions/$slug'
    | '/supplies/$slug'
    | '/artists/'
    | '/classes/'
    | '/exhibitions/'
    | '/supplies/'
    | '/_authenticated/dashboard/artworks'
    | '/_authenticated/dashboard/commissions'
    | '/_authenticated/dashboard/new-class'
    | '/_authenticated/dashboard/new-exhibition'
    | '/_authenticated/dashboard/new-supply'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/tickets'
    | '/_authenticated/dashboard/upload'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  CommissionsRoute: typeof CommissionsRoute
  ContactRoute: typeof ContactRoute
  ExhibitionsRoute: typeof ExhibitionsRouteWithChildren
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SellRoute: typeof SellRoute
  SuppliesRoute: typeof SuppliesRouteWithChildren
  TermsRoute: typeof TermsRoute
  ArtworksSlugRoute: typeof ArtworksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/': {
      id: '/supplies/'
      path: '/'
      fullPath: '/supplies/'
      preLoaderRoute: typeof SuppliesIndexRouteImport
      parentRoute: typeof SuppliesRoute
    }
    '/exhibitions/': {
      id: '/exhibitions/'
      path: '/'
      fullPath: '/exhibitions/'
      preLoaderRoute: typeof ExhibitionsIndexRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/classes/': {
      id: '/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/supplies/$slug': {
      id: '/supplies/$slug'
      path: '/$slug'
      fullPath: '/supplies/$slug'
      preLoaderRoute: typeof SuppliesSlugRouteImport
      parentRoute: typeof SuppliesRoute
    }
    '/exhibitions/$slug': {
      id: '/exhibitions/$slug'
      path: '/$slug'
      fullPath: '/exhibitions/$slug'
      preLoaderRoute: typeof ExhibitionsSlugRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/artworks/$slug': {
      id: '/artworks/$slug'
      path: '/artworks/$slug'
      fullPath: '/artworks/$slug'
      preLoaderRoute: typeof ArtworksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/upload': {
      id: '/_authenticated/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof AuthenticatedDashboardUploadRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tickets': {
      id: '/_authenticated/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof AuthenticatedDashboardTicketsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/new-supply': {
      id: '/_authenticated/dashboard/new-supply'
      path: '/new-supply'
      fullPath: '/dashboard/new-supply'
      preLoaderRoute: typeof AuthenticatedDashboardNewSupplyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/new-exhibition': {
      id: '/_authenticated/dashboard/new-exhibition'
      path: '/new-exhibition'
      fullPath: '/dashboard/new-exhibition'
      preLoaderRoute: typeof AuthenticatedDashboardNewExhibitionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/new-class': {
      id: '/_authenticated/dashboard/new-class'
      path: '/new-class'
      fullPath: '/dashboard/new-class'
      preLoaderRoute: typeof AuthenticatedDashboardNewClassRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/commissions': {
      id: '/_authenticated/dashboard/commissions'
      path: '/commissions'
      fullPath: '/dashboard/commissions'
      preLoaderRoute: typeof AuthenticatedDashboardCommissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/artworks': {
      id: '/_authenticated/dashboard/artworks'
      path: '/artworks'
      fullPath: '/dashboard/artworks'
      preLoaderRoute: typeof AuthenticatedDashboardArtworksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardArtworksRoute: typeof AuthenticatedDashboardArtworksRoute
  AuthenticatedDashboardCommissionsRoute: typeof AuthenticatedDashboardCommissionsRoute
  AuthenticatedDashboardNewClassRoute: typeof AuthenticatedDashboardNewClassRoute
  AuthenticatedDashboardNewExhibitionRoute: typeof AuthenticatedDashboardNewExhibitionRoute
  AuthenticatedDashboardNewSupplyRoute: typeof AuthenticatedDashboardNewSupplyRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardTicketsRoute: typeof AuthenticatedDashboardTicketsRoute
  AuthenticatedDashboardUploadRoute: typeof AuthenticatedDashboardUploadRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardArtworksRoute: AuthenticatedDashboardArtworksRoute,
    AuthenticatedDashboardCommissionsRoute:
      AuthenticatedDashboardCommissionsRoute,
    AuthenticatedDashboardNewClassRoute: AuthenticatedDashboardNewClassRoute,
    AuthenticatedDashboardNewExhibitionRoute:
      AuthenticatedDashboardNewExhibitionRoute,
    AuthenticatedDashboardNewSupplyRoute: AuthenticatedDashboardNewSupplyRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardTicketsRoute: AuthenticatedDashboardTicketsRoute,
    AuthenticatedDashboardUploadRoute: AuthenticatedDashboardUploadRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArtistsRouteChildren {
  ArtistsIdRoute: typeof ArtistsIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsIdRoute: ArtistsIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface ClassesRouteChildren {
  ClassesSlugRoute: typeof ClassesSlugRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesSlugRoute: ClassesSlugRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface ExhibitionsRouteChildren {
  ExhibitionsSlugRoute: typeof ExhibitionsSlugRoute
  ExhibitionsIndexRoute: typeof ExhibitionsIndexRoute
}

const ExhibitionsRouteChildren: ExhibitionsRouteChildren = {
  ExhibitionsSlugRoute: ExhibitionsSlugRoute,
  ExhibitionsIndexRoute: ExhibitionsIndexRoute,
}

const ExhibitionsRouteWithChildren = ExhibitionsRoute._addFileChildren(
  ExhibitionsRouteChildren,
)

interface SuppliesRouteChildren {
  SuppliesSlugRoute: typeof SuppliesSlugRoute
  SuppliesIndexRoute: typeof SuppliesIndexRoute
}

const SuppliesRouteChildren: SuppliesRouteChildren = {
  SuppliesSlugRoute: SuppliesSlugRoute,
  SuppliesIndexRoute: SuppliesIndexRoute,
}

const SuppliesRouteWithChildren = SuppliesRoute._addFileChildren(
  SuppliesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  ClassesRoute: ClassesRouteWithChildren,
  CommissionsRoute: CommissionsRoute,
  ContactRoute: ContactRoute,
  ExhibitionsRoute: ExhibitionsRouteWithChildren,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SellRoute: SellRoute,
  SuppliesRoute: SuppliesRouteWithChildren,
  TermsRoute: TermsRoute,
  ArtworksSlugRoute: ArtworksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
